# Authors: Matthew Olker, Spencer Peters, Chad Sigmon, Rahul
# Class: CSC3210

CREATE DATABASE `football_db`;

USE `football_db`;

DROP TABLE IF EXISTS `divisions`;

CREATE TABLE `divisions` (
	DIV_CODE int(11) NOT NULL UNIQUE,
	DIV_NAME varchar(40) NOT NULL,
	PRIMARY KEY(DIV_CODE)
	);

# Inserts

DROP TABLE IF EXISTS `teams`;

CREATE TABLE `teams` (
	TEAM_CODE int(11) NOT NULL UNIQUE,
	DIV_CODE int(11) NOT NULL,
	TEAM_NAME varchar(25) NOT NULL,
	TEAM_STATE char(2) NOT NULL,
	TEAM_CITY varchar(20) NOT NULL,
	TEAM_WINS int(3) NOT NULL,
	TEAM_LOSSES int(3) NOT NULL,
	TEAM_TIES int(3) NOT NULL,
	TEAM_SALARYCAP int(16) NOT NULL,
	PRIMARY KEY(TEAM_CODE),
	FOREIGN KEY(DIV_CODE) REFERENCES `divisions` (DIV_CODE) ON UPDATE CASCADE
);

# Inserts

DROP TABLE IF EXISTS `seasons`;

CREATE TABLE `seasons` (
	SEAS_YEAR int(11) NOT NULL UNIQUE,
	TEAM_CODE int(11) NOT NULL,
	PRIMARY KEY(SEAS_YEAR),
	FOREIGN KEY(TEAM_CODE) REFERENCES `teams` (TEAM_CODE) ON UPDATE CASCADE
);

# Inserts

DROP TABLE IF EXISTS `sponsors`;

CREATE TABLE `sponsors` (
	SPON_CODE int(11) NOT NULL UNIQUE,
	TEAM_CODE int(11) NOT NULL,
	SPON_NAME varchar(25) NOT NULL,
	SPON_STARTDATE date NOT NULL,
	SPON_ENDDATE date NOT NULL,
	SPON_RANK int(3) NOT NULL,
	PRIMARY KEY(SPON_CODE),
	FOREIGN KEY(TEAM_CODE) REFERENCES `teams` (TEAM_CODE) ON UPDATE CASCADE
);

# Inserts

DROP TABLE IF EXISTS `members`;

CREATE TABLE `members` (
	MEMBER_NUM int(11) NOT NULL UNIQUE,
	TEAM_CODE int(11) NOT NULL,
	MemberTypeId int REFERENCES MEMBERTYPE(MemberTypeId),
	MEMBER_FNAME varchar(25) NOT NULL,
	MEMBER_LNAME date NOT NULL,
	MEMBER_ADDRESS date NOT NULL,
	MEMBER_PHONE varchar(11) NOT NULL,
	PRIMARY KEY(MEMBER_NUM),
	FOREIGN KEY(TEAM_CODE) REFERENCES `teams` (TEAM_CODE) ON UPDATE CASCADE
	CONSTRAINT Member_AltPk UNIQUE (MEMBER_NUM, MemberTypeId)
);

# Inserts

DROP TABLE IF EXISTS `coaches`;

CREATE TABLE `coaches` (
	MEMBER_NUM int(11) NOT NULL UNIQUE,
	MemberTypeId AS 1 PERSISTED,
	COACH_REPORTSTO int(11) NOT NULL,
	COACH_ROLE varchar(20) NOT NULL,
	FOREIGN KEY(MEMBER_NUM, MemberTypeId) REFERENCES `members` (MEMBER_NUM, MemberTypeId) ON UPDATE CASCADE
);

# Inserts

DROP TABLE IF EXISTS `players`;

CREATE TABLE `players` (
	MEMBER_NUM int(11) NOT NULL UNIQUE,
	MemberTypeId AS 2 PERSISTED,
	COACH_REPORTSTO int(11) NOT NULL,
	COACH_ROLE varchar(20) NOT NULL,
	FOREIGN KEY(MEMBER_NUM, MemberTypeId) REFERENCES `members` (MEMBER_NUM, MemberTypeId) ON UPDATE CASCADE
);

# Inserts