insert into teams (TEAM_CODE, DIV_CODE, TEAM_NAME, TEAM_STATE, TEAM_CITY, TEAM_WINS, TEAM_LOSSES, TEAM_TIES, TEAM_SALARY) values (10, 1, 'Patriots', 'MA', 'Foxboro', 182, 493, 46, 5826209);
insert into teams (TEAM_CODE, DIV_CODE, TEAM_NAME, TEAM_STATE, TEAM_CITY, TEAM_WINS, TEAM_LOSSES, TEAM_TIES, TEAM_SALARY) values (11, 2, 'Ravens', 'MD', 'Baltimore', 149, 409, 97, 3183940);
insert into teams (TEAM_CODE, DIV_CODE, TEAM_NAME, TEAM_STATE, TEAM_CITY, TEAM_WINS, TEAM_LOSSES, TEAM_TIES, TEAM_SALARY) values (12, 3, 'Chargers', 'CA', 'San Diego', 87, 403, 76, 4195865);
insert into teams (TEAM_CODE, DIV_CODE, TEAM_NAME, TEAM_STATE, TEAM_CITY, TEAM_WINS, TEAM_LOSSES, TEAM_TIES, TEAM_SALARY) values (13, 4, 'Jaguars', 'FL', 'Jacksonville', 337, 182, 71, 14935361);
insert into teams (TEAM_CODE, DIV_CODE, TEAM_NAME, TEAM_STATE, TEAM_CITY, TEAM_WINS, TEAM_LOSSES, TEAM_TIES, TEAM_SALARY) values (14, 5, 'Saints', 'LA', 'New Orleans', 177, 24, 58, 7110920);
insert into teams (TEAM_CODE, DIV_CODE, TEAM_NAME, TEAM_STATE, TEAM_CITY, TEAM_WINS, TEAM_LOSSES, TEAM_TIES, TEAM_SALARY) values (15, 6, 'Packers', 'WI', 'Green Bay', 377, 256, 67, 10549951);
insert into teams (TEAM_CODE, DIV_CODE, TEAM_NAME, TEAM_STATE, TEAM_CITY, TEAM_WINS, TEAM_LOSSES, TEAM_TIES, TEAM_SALARY) values (16, 7, 'Cowboys', 'TX', 'Dallas', 367, 364, 83, 13890279);
insert into teams (TEAM_CODE, DIV_CODE, TEAM_NAME, TEAM_STATE, TEAM_CITY, TEAM_WINS, TEAM_LOSSES, TEAM_TIES, TEAM_SALARY) values (17, 8, 'Seahawks', 'WA', 'Seattle', 117, 356, 53, 14080903);
